apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdsquawk-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birdsquawk
  template:
    metadata:
      labels:
        app: birdsquawk
    spec:
      containers:
        - name: birdsquawk
          image: nelsonekpenyong/birdsquawk
---
apiVersion: v1
kind: Service
metadata:
  name: birdsquawk-service
spec:
  selector:
    app: birdsquawk
    type: ClusterIp
  ports:
   - name: birdsquawk
     protocol: TCP
     port: 500
     targetPort: 5000
